### PR TITLE
Initial commit for Cocos2d-Cordova-Crosswalk

### PR DESCRIPTION
**Pull request by kurli**

### CODE REVIEW

**Comment by kurli** [comment]
Hi @baleboy @bspencer @zhiqiangyu  @huningxin @halton 
Please have a review for this pull request, it's based on cordova-plugin-crosswalk-webview, and added cocos2d support. More info please refer the README file.

**Comment by halton** [comment]
@kurli This PR is so big and hard to review. Can you invite your peer (if has) to review instead?

**Comment by kurli** [comment]
Thanks @halton 
Hi @js0701 @gaochun, Please have a review.

**Comment by js0701** [comment]
LGTM

**Comment by halton** [comment]
Questions: 
1. Is the code copied from somewhere? Please leave the original info as much as possible. If forked from other CVS, please leave the original commit and history. Add your additional change in separate commit.
2. I saw some cocos logos imported as well. I think we need to be careful about that. @baleboy could suggest.
3. Has the code been through the open source review?

**Comment by kurli** [comment]
Thanks @halton 
I have separated the patch into several parts.
1. It's forked from crosswalk-cordova-android, I had just copied from crosswalk-10 branch.
2. The cocos logo is from cocos app template: https://github.com/cocos2d/cocos2d-html5/tree/develop/template I have added cocos2d licenses in this repo, is this OK?
3. We have finished open source review.

**Comment by halton** [comment]
> 1. It's forked from crosswalk-cordova-android, I had just copied from crosswalk-10 branch.

Since it is forked from crosswalk-cordova-android, why use separate repo instead of branching?

> 1. The cocos logo is from cocos app template: https://github.com/cocos2d/cocos2d-html5/tree/develop/template I have added cocos2d licenses in this repo, is this OK?

I do not have answer, my experience is the logos/assets need extra trademark checking besides open source review. @baleboy

**Comment by kurli** [comment]
HI @halton We have finished PDT review, and I think it's Ok for legal issue, can we merge this PR?

**Comment by kurli** [comment]
I will close this PR.
Our cocos2d optimization is based on crosswalk-cordova-android, will create a new branch on that repo, new PR link please visit: https://github.com/crosswalk-project/crosswalk-cordova-android/pull/169

**Comment by halton** [comment]
Thanks

**Pull request closed without merging**
